language: java

jdk:
  - oraclejdk8

services:
  - docker

addons:
  sonarqube: true

after_success:
  - ./gradlew jacocoTestReport coveralls
  - docker build -t sportchef/events .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push sportchef/events

env:
  global:
  - secure: HxW9gNpMlJ+NjrYzn/l/+BMUd9GMKzpBXqDky25b0pHnhv9CDycNwaOTaG6DFBVpgpePRxfyeIy8hoJiy9Lz0Dx6wxaktOmdABbPaCz3JB2oKsWBthHk5+nKU0N/QrhbvI1sAoY1VAownMWDgvAvuDsag7Iq/yOOMrKc8CUIJNaVQz6Iie5jmKjpVfIS6+OMriKb8E9uN2XjEjhw1VJnmBxfhE8AYTcYEYkM6UX4ccg8IBcuZrhpCkFoul3TMSXem2Wc6PRXGxGx5OhERFBsF/wfbVTZAaDnIiQaJsPHmd3EhotVhQXJxCghXRy9EQEpgoNQLFxG/YVKknESmUEjXHppXhEK/BmZBnYksWpYPs+mKVBjVDQPDXl4S2052Sd9el2nHUklOCdg/NaJJS0CDUTEv/rNFNnkrh/LPnJA3iMpoTWkhkoKxPDqJ6il1vZrX8qVnsIRcfwjtQTv4viIXazn7TECFa5Mx4BRx+O839KolV+/+Ly8CCbwahHhkcWY2i1i/5f8Jtf3FS6cdQ+9oejFY0YXvgDpOuzq+G1cQptlQ4Y/sxybmv6shLubUBpLVpvT2Tt6tZwRxORYzXQShLjWiHVkrUPXnQUGyDV0ZDaML2j3VMugLQebdW65qo/gmN06SW26IiEc7/hEsLSkJuv/RpYhDz5qerbdEs0Bxlg=
  - secure: fbSeLqLq+Uz2xoprMPsmikicOiZzuS1TUfT98D3bvOWQxJAnCdIv4gUBIWgJltrLvKXNhysV27yXEQPeYQERWi8EkD09jVhQqzXxsYpzrVzQqH8KZhnTPg/nkEpYOwBOfQb+P0Za14zg3Gb1NNjNEMtLj1RjVweojKGncUjCS+cLChbRi9Q5U+7OU+0edC0WrNyuSjHhcEDM1P9UcA7LVAM1HgiGNKas68Uz8AAnXQJ+Kpl5otoiOTEl/zgBmY0UEdCiMj1AVzV4edYsD+cOTJJqyD66CRcrQ6bKA+xoGJEuZSXoT5DR/VKQS7yvPmRwENIE5QLqQ1MpInxiExgm/5nqNGxSNxAa7R6i91aDYG0HtobNGUFpK5iMno5OA/MWfTOa8m/lvhNfoLAmngk52S0nglrDYxSRMvgZ+ts7g1GcgO13dppAY0whk4IPaxwvSt905JAK9CE2gMTEmvlK/SGVcedHg05l3JJ5wj2U5V3E+03VRkiaHmPC5g6u7DOtsA5uoH52YylQUm0YR0b1ToaxEMnTeXPulokdco9ho6ixaXcLUQ+yRqiAIzEZDS4pu5XGNBOYH/vh3/fWsMMs61kniGu2K3d2tkmo6jnJQ8ZISYyEkIWI9js1GU72N//Bo9wnddwPsjqbEbtk8qJZ1vhS96U10/vkJef8RdiBnQU=
  - secure: FQA4XfbVbmaQiAEUQ72QD23c/SWy8FeWFY62MAmxs9OLCDpLmmZxP7GQwr5H4uogg0bIgc5FUbKl5lhwwDxeYhUgK9/uVooMB0rqtwUmn4QS1JbDVCoElzUwvWkE5h3x0aXQt4ruGeC0xMPyL7yd6UCTLGvSyTfAGDp3f0Q84a6DkfVNHqsElio8Hxb1Hpi8B3HQPTvrA1uO5gyVLvR6OjNMtnLSV07R5BWx5fFPO9GjaerhmJmzfz730iaShnEWkQ3lh/C6w4eGNrzrQE5xRHCb8hzeRkOHEAFBjo3LVYLH6XN8PUFTSRoepNml7NcUicEJAzliETrykxL0PjMcvvqIXnmoZSQb74uhQRozNqGvxpvq2JCPw+g0dTOdYYzNt6IwzCU5H6rl1kZfQUEN3sQWsg460yTM+olflBT/FVLot/pkpdUfkHWDwpywWOIZo4omsd2PcF5jtpjq2iB+k5LXoDJyLYqgeXsi85m1d4ENKGCGDmllV8D0Xoesk/1neNQNUbaJc55XntfqH2ODxTONP+ftXgcdC55/akLJisvF0YCoZgVw7XVRw0Na1l2CAHCm/AuhY1TmnfoGh4F376ywURMsAdkq0dJpQnkClmxGZq2JOCAJXwsgZ+reLQBnS09s6T095+LG4gYstELTqxuYIyXDUFWguJrCDo9aeAU=

script:
  - ./gradlew check
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
